CHANGELOG.md, federation/hostmeta/generators.py, federation/hostmeta/schemas/nodeinfo-1.0.json, federation/tests/hostmeta/test_generators.py
Support for generating NodeInfo documents using the generator `federation.hostmeta.generators.NodeInfo`. Strict validation is skipped by default, but can be enabled by passing in `raise_on_validate` to the `NodeInfo` class. By default a warning will be generated on documents that don't conform with the strict NodeInfo values. This can be disabled by passing in `skip_validate` to the class.
Closes #11
=> Add support for NodeInfo document generation

CHANGELOG.md, setup.py
=> Bump lxml and python-dateutil dependencies

CHANGELOG.md, federation/protocols/diaspora/protocol.py, federation/tests/fixtures/payloads.py, federation/tests/protocols/diaspora/test_diaspora.py
Diaspora private messages don't have a plain text sender handle in the header. One must first
open the message (without verifying it), fetch the sender handle and then verify the content.
Closes #21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jaywink/social-federation/25)
=> Refactor Diaspora protocol sender handle fetching

CHANGELOG.md, federation/entities/base.py, federation/entities/diaspora/entities.py, federation/entities/diaspora/mappers.py, federation/tests/entities/diaspora/test_entities.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/entities/test_base.py, federation/tests/fixtures/payloads.py
Relationship base entity which represents relationships between two handles. Types can be following, sharing, ignoring and blocking. The Diaspora counterpart, DiasporaRequest, which represents a sharing/following request is outwards a single entity, but incoming a double entity, handled by creating both a sharing and following version of the relationship.
Closes #26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jaywink/social-federation/28)
=> Add Relationship entity

CHANGELOG.md, federation/controllers.py, federation/entities/diaspora/entities.py, federation/entities/diaspora/mappers.py, federation/entities/diaspora/utils.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/entities/diaspora/test_utils.py, federation/tests/test_controllers.py
When sending an entity, first convert it to the correct entity using the protocol entities. If a suitable entity is not found, raise an error.
Closes #27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jaywink/social-federation/30)
=> Convert outbound entities to correct protocol types

CHANGELOG.md, federation/fetchers.py, federation/hostmeta/generators.py, federation/hostmeta/templates/hcard_diaspora.html, federation/tests/hostmeta/test_generators.py, federation/tests/test_fetchers.py, federation/tests/utils/test_diaspora.py, federation/utils/diaspora.py, setup.py
High level method to fetch a remote profile. Currently falls back to Diaspora protocol as no others are supported.
Returns a Profile entity.
Closes #15
Also add 'guid' and 'public_key' as required for DiasporaHCard generator. Leaving these out was a mistake in the initial implementation. Diaspora has these in at least 0.6 development branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jaywink/social-federation/36)
=> Get remote profile method

CHANGELOG.md, federation/protocols/diaspora/protocol.py, federation/tests/protocols/diaspora/test_diaspora.py, federation/tests/test_outbound.py
* Don't quote/encode Protocol.build_send payload. It was doing it wrongly in the first place and also it's not necessary since Diaspora 0.6.
* Fix identification of Diaspora protocol messages. This was not working in the case that the attributes in the <diaspora> tag were in different order.
=> Fixes to Diaspora protocol handling

CHANGELOG.md, federation/outbound.py, federation/protocols/diaspora/protocol.py, federation/tests/protocols/diaspora/test_diaspora.py, federation/tests/test_outbound.py
Public content does not require a recipient.
=> Make to_user optional in handle_create_payload

CHANGELOG.md, federation/tests/utils/test_network.py, federation/utils/network.py
It's a wrapper around requests.post that adds the correct user agent and silently captures common requests exceptions and returns them instead.
=> Add send_document network utility

CHANGELOG.md, federation/protocols/diaspora/magic_envelope.py, federation/tests/protocols/diaspora/test_magic_envelope.py
New style Diaspora Magic Envelope didn't require or like payload data to be cut to 60 char lines, as the legacy protocol does. Fixed to not cut lines.
=> Fix new style Diaspora Magic Envelope payload data

CHANGELOG.md, federation/tests/utils/test_diaspora.py, federation/utils/diaspora.py
In the future diaspora hCard is not guaranteed to contain pod url or username. Don't rely on these in the parser, instead pass handle to the hCard parser directly.
Closes #50
=> Fix parsing profile from hCard

CHANGELOG.md, federation/entities/base.py, federation/entities/diaspora/entities.py, federation/entities/diaspora/mappers.py, federation/tests/entities/diaspora/test_entities.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/entities/test_base.py, federation/tests/fixtures/payloads.py
Changelog:
* Made `guid` mandatory for `Profile` entity. Library users should always be able to get a full validated object as we consider `guid` a core attribute of a profile.
* Always validate entities created through `federation.entities.diaspora.mappers.message_to_objects`. This is the code that transforms federation messages for the Diaspora protocol to actual entity objects. Previously no validation was done and callers of `federation.inbound.handle_receive` received entities that were not always valid, for example they were missing a `guid`. Now validation is done in the conversion stage and errors are pushed to the `social-federation` logger in the event of invalid messages.
* Note Diaspora Profile XML messages do not provide a GUID. This is handled internally by fetching the guid …
=> Various improvements to entity validation

CHANGELOG.md, federation/fetchers.py, federation/tests/utils/test_diaspora.py, federation/utils/diaspora.py
* `federation.utils.diaspora.retrieve_and_parse_profile` will now return `None` if the `Profile` retrieved doesn't validate. This will affect also the output of `federation.fetchers.retrieve_remote_profile` which is the high level function to retrieve profiles.
* Remove unnecessary `protocol` parameter from `federation.fetchers.retrieve_remote_profile`. We're miles away from including other protocols and ideally the caller shouldn't have to pass in the protocol anyway.
Closes #54
=> Validate fetched remote profile

CHANGELOG.md, federation/entities/base.py, federation/entities/diaspora/mappers.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/entities/test_base.py, federation/tests/fixtures/payloads.py
Diaspora photo elements are now processed correctly. Inbound parsing has been changed to also correctly add them to created entities as children, if they happen to be embedded in status messages, for example. Entity children can be iterated using the `_children` list.
Also rename the `Image.text` attribute to `Image.raw_content` to be more consistent.
Closes #62
=> Fix Diaspora photo support and allow entities to have children

CHANGELOG.md, federation/entities/base.py, federation/tests/utils/test_diaspora.py
This fixes validating profiles parsed from Diaspora hCard's.
=> Made Profile.raw_content optional

CHANGELOG.md, dev-requirements.txt, federation/entities/diaspora/mappers.py, federation/entities/diaspora/utils.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/entities/diaspora/test_utils.py, federation/tests/fixtures/payloads.py
Diaspora protocol changed to  ISO 8601 timestamp format in protocol version 0.1.6.
Closes #67
=> Add support for new Diaspora timestamp format

CHANGELOG.md, docs/usage.rst, federation/outbound.py, federation/tests/conftest.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/test_outbound.py, federation/utils/diaspora.py
Allows sending a single entity to multiple receivers. Currently public Diaspora entities supported.
=> Add handle_send outbound helper

CHANGELOG.md, federation/entities/base.py, federation/entities/diaspora/mappers.py, federation/inbound.py, federation/tests/entities/diaspora/test_mappers.py
Required for example to actually use (legacy) relationship retraction.
=> Add receiving user guid to entity for private Diaspora payloads

CHANGELOG.md, federation/protocols/base.py, federation/protocols/diaspora/encrypted.py, federation/protocols/diaspora/magic_envelope.py, federation/protocols/diaspora/protocol.py, federation/tests/protocols/diaspora/test_encrypted.py, federation/tests/protocols/diaspora/test_protocol.py, federation/tests/utils/test_text.py, federation/utils/text.py
Support receiving the new style Diaspora encrypted JSON payloads. Sending is part of #82 
TODO:
Closes #83
=> Support receiving new style Diaspora encrypted payloads

CHANGELOG.md, dev-requirements.txt, federation/entities/base.py, federation/entities/diaspora/entities.py, federation/entities/diaspora/mappers.py, federation/entities/diaspora/utils.py, federation/protocols/diaspora/protocol.py, federation/tests/entities/diaspora/test_entities.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/entities/diaspora/test_utils.py, federation/tests/protocols/diaspora/test_protocol.py
Add created_at to Diaspora Comment entity XML creator (refs: #59)
Store the original object when signing with parent, then use that for sending, not serializing our entity object. This fixes relayable support broken with the new Diaspora protocol.
=> Add created_at to Diaspora Comment entity XML creator + fix relayable support

CHANGELOG.md, federation/entities/diaspora/entities.py, federation/outbound.py, federation/tests/conftest.py, federation/tests/entities/diaspora/test_entities.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/test_outbound.py
**Breaking change.** The high level `federation.outbound` functions `handle_send` and `handle_create_payload` signatures have been changed. This has been done to better represent the objects that are actually sent in and to add an optional `parent_user` object.
For both functions the `from_user` parameter has been renamed to `author_user`. Optionally a `parent_user` object can also be passed in. Both the user objects must have `private_key` and `handle` attributes. In the case that `parent_user` is given, that user will be used to sign the payload and for Diaspora relayables an extra `parent_author_signature` in the payload itself.
=> Refactor handle_send and handle_create_payload signatures

CHANGELOG.md, federation/entities/diaspora/mappers.py, federation/inbound.py, federation/tests/entities/diaspora/test_entities.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/fixtures/payloads.py
Add proper checks to make sure Diaspora protocol payload handle and entity handle are the same. Even though we already verified the signature of the sender, we didn't ensure that the sender isn't trying to fake an entity authored by someone else.
The Diaspora protocol functions `message_to_objects` and `element_to_objects` now require a new parameter, the payload sender handle. These functions should normally not be needed to be used directly.
=> Verify payload and entity handle are the same

CHANGELOG.md, federation/entities/diaspora/mappers.py
Due to security fix in 0.14.0. Payload and entity handle need to be allowed to be different when handling relayables.
=> Fix regression in handling Diaspora relayables

CHANGELOG.md, federation/entities/base.py, federation/tests/entities/diaspora/test_utils.py
Converting base entity `Profile` to `DiasporaProfile` for outbound sending missed two attributes, `image_urls` and `tag_list`. Those are now included so that the values transfer into the built payload.
=> Fix DiasporaProfile.from_base

CHANGELOG.md, docs/protocols.rst, docs/usage.rst, federation/entities/base.py, federation/entities/diaspora/entities.py, federation/entities/diaspora/mappers.py, federation/tests/entities/diaspora/test_entities.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/entities/test_base.py, federation/tests/factories/entities.py, federation/tests/fixtures/payloads.py
Maps to a `DiasporaReshare` for the Diaspora protocol.
The `Share` entity supports all the properties that a Diaspora reshare does. Additionally two other properties are supported: `raw_content` and `entity_type`. The former can be used for a "quoted share" case where the sharer adds their own note to the share. The latter can be used to reference the type of object that was shared, to help the receiver, if it is not sharing a `Post` entity. The value must be a base entity class name.
TODO:
Closes #94
=> Added base entity Share

CHANGELOG.md, docs/usage.rst, federation/entities/base.py, federation/entities/diaspora/entities.py, federation/entities/diaspora/mappers.py, federation/fetchers.py, federation/protocols/diaspora/magic_envelope.py, federation/protocols/diaspora/protocol.py, federation/tests/conftest.py, federation/tests/entities/diaspora/test_entities.py, federation/tests/fixtures/diaspora.py, federation/tests/fixtures/keys.py, federation/tests/protocols/diaspora/test_magic_envelope.py, federation/tests/protocols/diaspora/test_protocol.py, federation/tests/protocols/diaspora/test_signatures.py, federation/tests/test_fetchers.py, federation/tests/utils/test_diaspora.py, federation/utils/diaspora.py
The given ID will be fetched using the correct entity class specific remote endpoint, validated to be from the correct author against their public key and then an instance of the entity class will be constructed and returned.
Also related changes and refactoring:
* New Diaspora protocol helper `federation.utils.diaspora.retrieve_and_parse_content`. See notes regarding the high level fetcher above.
* New Diaspora protocol helper `federation.utils.fetch_public_key`. Given a `handle` as a parameter, will fetch the remote profile and return the `public_key` from it.
* Refactoring for Diaspora `MagicEnvelope` class.
* Diaspora procotol receive flow now uses the `MagicEnvelope` class to verify payloads.
* Diaspora protocol receive flow now fetches the sender public key over the network if a …
=> New high level fetcher function retrieve_remote_content

federation/entities/diaspora/entities.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/fixtures/payloads.py
Diaspora removed 'public' from reshare in protocol version 0.2.2. Since we do support it, when parsing incoming payloads, set it to True if it is missing. Our Share base entity defaults to False.
=> Ensure DiasporaReshare.public is set

CHANGELOG.md, federation/fetchers.py, federation/tests/test_fetchers.py
Using `retrieve_remote_profile`. Warning will be logged if an upper case handle is passed in.
=> Ensure handle is always lower cased when fetching remote profile

CHANGELOG.md, federation/tests/fixtures/payloads.py, federation/tests/hostmeta/test_generators.py, federation/tests/utils/test_diaspora.py, federation/utils/diaspora.py
The legaxy Webfinger is still used as fallback if the new Webfinger is not found.
Refs: #108
=> Support fetching new style Diaspora protocol Webfinger (RFC 3033)

CHANGELOG.md, federation/protocols/diaspora/protocol.py, federation/tests/protocols/diaspora/test_protocol.py
Remove possibility to generate legacy MagicEnvelope payloads.
Refs: #82
=> Send outbound Diaspora payloads in new format

CHANGELOG.md, docs/usage.rst, federation/outbound.py, federation/protocols/diaspora/encrypted.py, federation/protocols/diaspora/protocol.py, federation/tests/protocols/diaspora/test_encrypted.py, federation/tests/protocols/diaspora/test_protocol.py, federation/tests/test_outbound.py, federation/tests/utils/test_diaspora.py, federation/utils/diaspora.py, federation/utils/network.py
* Enable generating encrypted JSON payloads with the Diaspora protocol
This adds possibility for private message support. JSON encrypted payload encryption and decryption is handled by the Diaspora `EncryptedPayload` class.
* Refactor handle_send function
Now handle_send high level outbound helper function also allows delivering private payloads using the Diaspora protocol.
Refs: #82
=> Enable delivery of new style private messages using Diaspora protocol

CHANGELOG.md, dev-requirements.txt, docs/usage.rst, federation/hostmeta/django/__init__.py, federation/hostmeta/django/generators.py, federation/hostmeta/django/urls.py, federation/hostmeta/generators.py, federation/tests/hostmeta/django/settings.py, federation/tests/hostmeta/django/test_generators.py, federation/tests/hostmeta/django/utils.py, federation/tests/hostmeta/test_generators.py, federation/tests/utils/test_diaspora.py, federation/utils/diaspora.py, pytest.ini
Also provided is a Django view and url configuration for easy addition into Django projects. Django is not a hard dependency of this library, usage of the Django view obviously requires installing Django itself. For configuration details see documentation.
TODO:
Closes #108
=> Add RFC3033 webfinger generator

CHANGELOG.md, federation/entities/diaspora/entities.py, federation/tests/entities/diaspora/test_entities.py, federation/tests/entities/diaspora/test_utils.py
We've already accepted these on incoming payloads for a long time and so do all the other platforms now, so now we always send out entities with the new property names. This can break federation with really old servers that don't understand these keys yet.
Closes #59
=> Switch Diaspora protocol to send new style entities

CHANGELOG.md, docs/usage.rst, federation/tests/hostmeta/test_parsers.py, federation/tests/utils/test_network.py, federation/utils/network.py
Network utils has a method `fetch_host_ip_and_country` which will
fetch both. The country fetching uses the `ip-api.com` free service
to resolve country information.
=> Add fetching of IP and country

CHANGELOG.md, federation/entities/base.py, federation/entities/diaspora/entities.py, federation/entities/diaspora/mappers.py, federation/tests/entities/diaspora/test_entities.py, federation/tests/entities/diaspora/test_mappers.py, federation/tests/fixtures/payloads.py
The mentions will be available in the entity as `_mentions` which is
a set of Diaspora ID's in URI format.
=> Extract mentions from Diaspora payloads that have text content
